### ISSUE TITLE
java.lang.IllegalArgumentException when executing 'coverageAggregate'

### ISSUE THREAD

**Issue by kamilkloch** [scoverage/sbt-scoverage#104]
sbt-coverage v. 1.1.0

```
> coverageAggregate
[info] Aggregating coverage from subprojects...
[info] Found 8 subproject report files [/home/kamilk/tmp/project-4/target/scala-2.11/scoverage-report/scoverage.xml,/home/kamilk/tmp/project-4/lib/target/scala-2.11/scoverage-report/scoverage.xml,/home/kamilk/tmp/project-4/jppfcluster/target/scala-2.11/scoverage-report/scoverage.xml,/home/kamilk/tmp/project-4/runtime/target/scala-2.11/scoverage-report/scoverage.xml,/home/kamilk/tmp/project-4/users/target/scala-2.11/scoverage-report/scoverage.xml,/home/kamilk/tmp/project-4/sample/target/scala-2.11/scoverage-report/scoverage.xml,/home/kamilk/tmp/project-4/api/target/scala-2.11/scoverage-report/scoverage.xml,/home/kamilk/tmp/project-4/bokehplot/target/scala-2.11/scoverage-report/scoverage.xml]
[trace] Stack trace suppressed: run last root/*:coverageAggregate for the full output.
[error] (root/*:coverageAggregate) java.lang.IllegalArgumentException: For input string: ""
[error] Total time: 0 s, completed Apr 27, 2015 2:10:50 PM
> last root/*:coverageAggregate
java.lang.IllegalArgumentException: For input string: ""
	at scala.collection.immutable.StringLike$class.parseBoolean(StringLike.scala:238)
	at scala.collection.immutable.StringLike$class.toBoolean(StringLike.scala:226)
	at scala.collection.immutable.StringOps.toBoolean(StringOps.scala:31)
	at scoverage.report.ScoverageXmlReader$$anonfun$read$1.apply(ScoverageXmlReader.scala:57)
	at scoverage.report.ScoverageXmlReader$$anonfun$read$1.apply(ScoverageXmlReader.scala:19)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scoverage.report.ScoverageXmlReader$.read(ScoverageXmlReader.scala:19)
	at scoverage.report.CoverageAggregator$$anonfun$aggregatedCoverage$1.apply(CoverageAggregator.scala:29)
	at scoverage.report.CoverageAggregator$$anonfun$aggregatedCoverage$1.apply(CoverageAggregator.scala:28)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scoverage.report.CoverageAggregator$.aggregatedCoverage(CoverageAggregator.scala:28)
	at scoverage.report.CoverageAggregator$.aggregate(CoverageAggregator.scala:17)
	at scoverage.ScoverageSbtPlugin$$anonfun$projectSettings$16.apply(ScoverageSbtPlugin.scala:74)
	at scoverage.ScoverageSbtPlugin$$anonfun$projectSettings$16.apply(ScoverageSbtPlugin.scala:69)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (root/*:coverageAggregate) java.lang.IllegalArgumentException: For input string: ""
```

**Comment by gslowikowski** [comment]
From the stack trace (https://github.com/scoverage/scalac-scoverage-plugin/blob/1.1.0/scalac-scoverage-plugin/src/main/scala/scoverage/report/ScoverageXmlReader.scala#L57), this issue is related/caused by https://github.com/scoverage/scalac-scoverage-plugin/pull/117.

Did you cleaned your project before first run with `1.1.0`?

**Comment by kamilkloch** [comment]
Thanks, @gslowikowski. `git clean -xdf` did the job.
