### ISSUE TITLE
"RuntimeException: No source root found for ... src_managed ..." when generating report

### ISSUE THREAD

**Issue by dragisak** [scoverage/sbt-scoverage#105]
It's a multi-module project, sbt-scoverage 1.1.0

Output for `sbt clean coverage test it:test`:

```
java.lang.RuntimeException: No source root found for '/Users/dragisak/Ticketfly/DVA/core/target/scala-2.11/src_managed/reflect/Reflect.scala' (source roots: '/Users/dragisak/Ticketfly/DVA/core/src/main/scala/')
	at scoverage.report.BaseReportWriter.relativeSource(BaseReportWriter.scala:26)
	at scoverage.report.BaseReportWriter.relativeSource(BaseReportWriter.scala:16)
	at scoverage.report.CoberturaXmlWriter.klass(CoberturaXmlWriter.scala:42)
	at scoverage.report.CoberturaXmlWriter$$anonfun$pack$1.apply(CoberturaXmlWriter.scala:66)
	at scoverage.report.CoberturaXmlWriter$$anonfun$pack$1.apply(CoberturaXmlWriter.scala:66)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scoverage.report.CoberturaXmlWriter.pack(CoberturaXmlWriter.scala:66)
	at scoverage.report.CoberturaXmlWriter$$anonfun$xml$3.apply(CoberturaXmlWriter.scala:90)
	at scoverage.report.CoberturaXmlWriter$$anonfun$xml$3.apply(CoberturaXmlWriter.scala:90)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scoverage.report.CoberturaXmlWriter.xml(CoberturaXmlWriter.scala:90)
	at scoverage.report.CoberturaXmlWriter.write(CoberturaXmlWriter.scala:21)
	at scoverage.ScoverageSbtPlugin.scoverage$ScoverageSbtPlugin$$writeReports(ScoverageSbtPlugin.scala:187)
	at scoverage.ScoverageSbtPlugin$$anonfun$postTestReport$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(ScoverageSbtPlugin.scala:135)
	at scoverage.ScoverageSbtPlugin$$anonfun$postTestReport$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(ScoverageSbtPlugin.scala:134)
	at scala.Option.foreach(Option.scala:236)
	at scoverage.ScoverageSbtPlugin$$anonfun$postTestReport$1$$anonfun$apply$1.apply$mcV$sp(ScoverageSbtPlugin.scala:133)
	at sbt.Tests$$anonfun$Cleanup$1.apply(Tests.scala:53)
	at sbt.Tests$$anonfun$Cleanup$1.apply(Tests.scala:53)
	at sbt.Tests$$anonfun$sbt$Tests$$partApp$1$1$$anonfun$apply$1.apply$mcV$sp(Tests.scala:160)
	at sbt.Tests$$anonfun$sbt$Tests$$fj$1$1.apply(Tests.scala:159)
	at sbt.Tests$$anonfun$sbt$Tests$$fj$1$1.apply(Tests.scala:159)
	at sbt.std.TaskExtra$$anon$1$$anonfun$fork$1$$anonfun$apply$1.apply(TaskExtra.scala:99)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gslowikowski** [comment]
Can you share your project? If not, tell how is 'Reflect.scala' file generated and added to sources without creating new source root, or being added to predefined 'target/scala_2.11/src_managed/main' source root (not included in error message because scoverage ignores non existent or empty ones)

**Comment by dragisak** [comment]
It's generated via a plugin. I have access to plugin's source code. So, I'll checks where it places files.

**Comment by dragisak** [comment]
I am closing this. When generated code is in proper place, it works fine.

**Comment by rleibman** [comment]
How did you solve it? (I"m using reflected as well) how do you put the generated code in the right place, and what is the right place?

**Comment by dragisak** [comment]
It was a custom plugin that I wrote that was generating source files in the wrong directory.

**Comment by rleibman** [comment]
Thanks got it. I'm using sbt-reflect, and it also puts files in the wrong directory, I made some changes and got it to work.

**Comment by dragisak** [comment]
We eventually switched to sbt-buildinfo

**Comment by rleibman** [comment]
Thanks, that looks much better supported, I think I'll use that instead.
