### ISSUE TITLE
publish to central or wherever

### ISSUE THREAD

**Issue by fommil** [scoverage/sbt-scoverage#137]
```
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scoverage#sbt-scoverage;1.3.1: not found
```

somebody got there with a different artefact

http://search.maven.org/#search%7Cga%7C1%7Csbt-scoverage

**Comment by sksamuel** [comment]
At least we know twitter use it :) I didn't know you could push sbt to central, I'll start doing that instead of silly bitworld or whatever its called.

**Comment by sksamuel** [comment]
bintray

**Comment by fommil** [comment]
I publish my plugins to central actually. If its not on central, it doesn't exist. That said, I've never been able to get the sbt release plugin working properly.

I'm looking at `sbt-coveralls` today btw

**Comment by sksamuel** [comment]
I'm gonna start doing that and naff off bintray because I can never get it to sync with the sbt one. Are you on gitter?

**Comment by fommil** [comment]
@sksamuel yup

**Comment by sksamuel** [comment]
1.3.2 is released with the fixes. This release is on maven central on bintray.

**Comment by fommil** [comment]
computer says no http://search.maven.org/#search%7Cga%7C1%7Csbt-scoverage

**Comment by fommil** [comment]
did you remember to do the close/release dance at oss.sonatype.org ?

**Comment by sksamuel** [comment]
Can take 12 hours to appear in search but should resolve immediately.

**Comment by fommil** [comment]
nope, I get resolve errors

**Comment by fommil** [comment]
```
sbt 
[info] Loading global plugins from /home/fommil/.sbt/0.13/plugins
[info] Loading project definition from /home/fommil/Projects/ensime-server/project
[info] Updating {file:/home/fommil/Projects/ensime-server/project/}ensime-server-build...
[info] Resolving org.scoverage#sbt-scoverage;1.3.2 ...
[warn] 	module not found: org.scoverage#sbt-scoverage;1.3.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.3.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.3.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/fommil/.ivy2/local/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.3.2/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/org/scoverage/sbt-scoverage_2.10_0.13/1.3.2/sbt-scoverage-1.3.2.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.10_0.13/1.3.2/sbt-scoverage-1.3.2.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scoverage#sbt-scoverage;1.3.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.scoverage:sbt-scoverage:1.3.2 (sbtVersion=0.13, scalaVersion=2.10)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scoverage:sbt-scoverage:1.3.2 (sbtVersion=0.13, scalaVersion=2.10) (/home/fommil/Projects/ensime-server/project/plugins.sbt#L13-14)
[warn] 		  +- default:ensime-server-build:0.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
sbt.ResolveException: unresolved dependency: org.scoverage#sbt-scoverage;1.3.2: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scoverage#sbt-scoverage;1.3.2: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

**Comment by fommil** [comment]
I don't trust that release plugin

**Comment by sksamuel** [comment]
Hmm ok i deffo had it released in nexus. I'll check when home i have had
issues before where releases disappear.

**Comment by gslowikowski** [comment]
Ivy-style release in Maven-style repo - http://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.10_0.13/1.3.2/
I don't like it

**Comment by gslowikowski** [comment]
SBT tries to find https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.10_0.13/1.3.2/sbt-scoverage-1.3.2.pom

**Comment by fommil** [comment]
This kind of publishing works for my SBT plugins. Look at ensime-sbt and lions share for examples.

**Comment by gslowikowski** [comment]
because you have publishMavenStyle set to true in ensime-sbt project.

**Comment by fommil** [comment]
Then that sounds like the fix.

**Comment by sksamuel** [comment]
So let me set that and do a 1.3.4 release

**Comment by gslowikowski** [comment]
Why `1.3.4`, where is `1.3.3`?

**Comment by sksamuel** [comment]
I meant 1.3.3 :)

**Comment by sksamuel** [comment]
Ok 1.3.3 is released to central if you want to try now @gslowikowski @fommil

**Comment by saurfang** [comment]
worked for me! thanks @sksamuel

**Comment by fommil** [comment]
yay! coveralls next :-)

**Comment by fommil** [comment]
oh, but actually coveralls still doesn't work for multiple module projects.
