### ISSUE TITLE
Can't run scoverage on a project with a ScalaJS projectToRef

### ISSUE THREAD

**Issue by schmitch** [scoverage/sbt-scoverage#152]
Hello, currently I try to run scoverage on a project that aggregates a client proejct with projectToRef.

It uses a configuration like that: https://github.com/vmunier/play-with-scalajs-example to generate the aggregated project.

Currently I always get the following when running `sbt coverage test`

```
java.lang.RuntimeException: There were linking errors
    at scala.sys.package$.error(package.scala:27)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:108)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:74)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:117)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:117)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:116)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:97)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$optimizeCP$1.apply$mcV$sp(ScalaJSOptimizer.scala:74)
    at org.scalajs.core.tools.io.CacheUtils$.cached(CacheUtils.scala:41)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeCP(ScalaJSOptimizer.scala:72)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$20.apply(ScalaJSPluginInternal.scala:276)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$20.apply(ScalaJSPluginInternal.scala:260)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: There were linking errors
    at scala.sys.package$.error(package.scala:27)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:108)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:74)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:117)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:117)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:116)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:97)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$optimizeCP$1.apply$mcV$sp(ScalaJSOptimizer.scala:74)
    at org.scalajs.core.tools.io.CacheUtils$.cached(CacheUtils.scala:41)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeCP(ScalaJSOptimizer.scala:72)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$20.apply(ScalaJSPluginInternal.scala:276)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$20.apply(ScalaJSPluginInternal.scala:260)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: There were linking errors
    at scala.sys.package$.error(package.scala:27)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:108)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:74)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$18.apply(ScalaJSPluginInternal.scala:243)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$18.apply(ScalaJSPluginInternal.scala:234)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

```

Currently sbt test works fine.

**Comment by ayushmishra2005** [comment]
I am also facing same issue.

**Comment by ckipp01** [comment]
Seeing that this was pretty old I'm going to close. Feel free to re-open if this is still an issue.
