### ISSUE TITLE
Position Error: Enclosing tree [2507] does not include tree [2506]

### ISSUE THREAD

**Issue by Richard-W** [scoverage/sbt-scoverage#156]
**What**: `sbt clean coverage test` fails, while `sbt clean test` succeeds
**Version**: 1.3.5
**How to reproduce**: Checkout richard-w/azas revision `60c3ff751630e7ff377bf5ed1f663f2cb99db23d` and run `sbt clean coverage test`

**Full error output** (note that scalariform complains too):
```
richard@neptun ~/src/azas $ sbt clean coverage test
[info] Loading project definition from /home/richard/src/azas/project
[info] Set current project to azas (in build file:/home/richard/src/azas/)
[success] Total time: 0 s, completed 08.02.2016 11:16:53
[info] Set current project to azas (in build file:/home/richard/src/azas/)
[info] Updating {file:/home/richard/src/azas/}azas...
[info] Formatting 3 Scala sources {file:/home/richard/src/azas/}azas(test) ...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Formatting 22 Scala sources {file:/home/richard/src/azas/}azas(compile) ...
[warn] Scalariform parser error for /home/richard/src/azas/src/main/scala/xyz/wiedenhoeft/azas/controllers/RestService.scala: Expected token SEMI but got Token(ARROW,⇒,1730,⇒)
[info] Compiling 22 Scala sources to /home/richard/src/azas/target/scala-2.11/classes...
[info] ======= Position error
[info] Enclosing tree [2507] does not include tree [2506]
[info] == Enclosing tree [2507] of type TypeApply at [1951:2021]RestService.scala
[info] 
[info] [L  56        ] #2507   [1951:2021]     TypeApply  // map[ToResponseMarshallable] { res ⇒
[info] 
[info] == Enclosed tree [2506] of type Select at [1951:2047]RestService.scala
[info] 
[info] [L  58        ] #2506   [1951:2047]     Select     // recover[ToResponseMarshallable] {
[info] 
[info] 
[info] While validating #3186
[info] [L  17        ] #3186   [740:7148]      PackageDef // controllers
[info] 
[info] Children:
[info]   [L  17 P# 3186] #2324   [748:780]       Select     // controllers
[info]   [L  19 P# 3186] #2328   [782:821]       Import     // spray.http.HttpHeaders.RawHeader
[info]   [L  20 P# 3186] #2331   [822:844]       Import     // spray.routing._
[info]   [L  21 P# 3186] #2334   [845:864]       Import     // spray.http._
[info]   [L  22 P# 3186] #2338   [865:897]       Import     // spray.httpx.marshalling._
[info]   [L  23 P# 3186] #2342   [898:932]       Import     // spray.httpx.unmarshalling._
[info]   [L  24 P# 3186] #2346   [933:970]       Import     // spray.httpx.SprayJsonSupport._
[info]   [L  25 P# 3186] #2349   [971:990]       Import     // spray.json._
[info]   [L  27 P# 3186] #2351   [992:1013]      Import     // JsonProtocol._
[info]   [L  28 P# 3186] #2356   [1014:1072]     Import     // xyz.wiedenhoeft.azas.models.{ Mascot, Participant }
[info]   [L  29 P# 3186] #2361   [1073:1108]     Import     // xyz.wiedenhoeft.azas.views._
[info]   [L  31 P# 3186] #2364   [1110:1135]     Import     // scala.concurrent._
[info]   [L  32 P# 3186] #2367   [1136:1179]     Import     // scala.util.{ Failure, Success, Try }
[info]   [L  34 P# 3186] #3185   [1181:7148]     ClassDef   // RestService extends HttpService {
[info] =======
scala.reflect.internal.Positions$ValidateException: Enclosing tree [2507] does not include tree [2506]
	at scala.reflect.internal.Positions$class.positionError$1(Positions.scala:102)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:124)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validatePositions(Positions.scala:147)
	at scala.reflect.internal.SymbolTable.validatePositions(SymbolTable.scala:16)
	at scala.tools.nsc.ast.parser.SyntaxAnalyzer$ParserPhase.apply(SyntaxAnalyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:398)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:398)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
	at sbt.inc.Incremental$.compile(Incremental.scala:61)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:128)
	at sbt.Compiler$.compile(Compiler.scala:114)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:829)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:820)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:818)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:compileIncremental) scala.reflect.internal.Positions$ValidateException: Enclosing tree [2507] does not include tree [2506]
[error] Total time: 5 s, completed 08.02.2016 11:16:58
```

**Comment by ymeymann** [comment]
Having the same issue

**Comment by akara** [comment]
This post reflects the same issue, with a workaround. Might be a similar use case.
https://groups.google.com/d/msg/scala-code-coverage-tool/Z7TisR6TrR8/QaPehhx2BgAJ

**Comment by ymeymann** [comment]
Thanks @akara, the workaround fixed the issue for me.

**Comment by xuanzhaopeng** [comment]
I could provide more information:
Scala : 2.11.8
SBT: 0.13.12
scoverage: 1.3.5

Same error.

**Comment by sksamuel** [comment]
This is a bug with the scalac plugin. I'll create a ticket over there.
