### ISSUE TITLE
Publishing scoverage report in Jenkins returns NoSuchElementException

### ISSUE THREAD

**Issue by krishhnaiyer** [scoverage/sbt-scoverage#226]
Hi All,

I ran some tests against in Jenkins and in the post build step of collecting scoverage report fails with NoSuchElementException,

Publishing Scoverage XML and HTML report ...
ERROR: Build step failed with exception
java.util.NoSuchElementException
	at java.util.LinkedList$ListItr.next(LinkedList.java:890)
	at org.jenkinsci.plugins.scoverage.ScoveragePublisher$ScovFinder.invoke(ScoveragePublisher.java:91)
	at org.jenkinsci.plugins.scoverage.ScoveragePublisher$ScovFinder.invoke(ScoveragePublisher.java:71)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2719)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to jenkinshost09(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at hudson.FilePath.act(FilePath.java:979)
	at hudson.FilePath.act(FilePath.java:968)
	at org.jenkinsci.plugins.scoverage.ScoveragePublisher.copyReport(ScoveragePublisher.java:106)
	at org.jenkinsci.plugins.scoverage.ScoveragePublisher.perform(ScoveragePublisher.java:66)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Publish Scoverage Report' marked build as failure

Can some please help resolve this issue ?

Regards,
Krishh

**Comment by silvestre-abruzzo** [comment]
I have exactly the same issue, any idea how to solve it ?

**Comment by ckipp01** [comment]
I'm going to go ahead and close this seeing that it's quite old and I also regularly use scoverage in Jenkins. If this does pop up again, please do report back.
