### ISSUE TITLE
Write aggregate report throw exception: java.nio.charset.MalformedInputException: Input length = 1 

### ISSUE THREAD

**Issue by Alex-Yu** [scoverage/sbt-scoverage#239]
Similar to this one: https://github.com/scoverage/scoverage-maven-plugin/issues/45

12:58:22 java.nio.charset.MalformedInputException: Input length = 1
12:58:22 at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
12:58:22 at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
12:58:22 at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
12:58:22 at java.io.InputStreamReader.read(InputStreamReader.java:184)
12:58:22 at java.io.BufferedReader.fill(BufferedReader.java:161)
12:58:22 at java.io.BufferedReader.read(BufferedReader.java:182)
12:58:22 at scala.io.BufferedSource$$anonfun$iter$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(BufferedSource.scala:38)
12:58:22 at scala.io.Codec.wrap(Codec.scala:68)
12:58:22 at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
12:58:22 at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
12:58:22 at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
12:58:22 at scala.collection.Iterator$$anon$17.hasNext(Iterator.scala:511)
12:58:22 at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
12:58:22 at scala.io.Source.hasNext(Source.scala:226)
12:58:22 at scala.collection.Iterator$class.foreach(Iterator.scala:727)
12:58:22 at scala.io.Source.foreach(Source.scala:178)
12:58:22 at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:320)
12:58:22 at scala.io.Source.addString(Source.scala:178)
12:58:22 at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:286)
12:58:22 at scala.io.Source.mkString(Source.scala:178)
12:58:22 at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:288)
12:58:22 at scala.io.Source.mkString(Source.scala:178)
12:58:22 at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:290)
12:58:22 at scala.io.Source.mkString(Source.scala:178)
12:58:22 at scoverage.report.CodeGrid.source(CodeGrid.scala:80)
12:58:22 at scoverage.report.CodeGrid.<init>(CodeGrid.scala:22)
12:58:22 at scoverage.report.ScoverageHtmlWriter.filePage(ScoverageHtmlWriter.scala:84)
12:58:22 at scoverage.report.ScoverageHtmlWriter.scoverage$report$ScoverageHtmlWriter$$writeFile(ScoverageHtmlWriter.scala:50)
12:58:22 at scoverage.report.ScoverageHtmlWriter$$anonfun$scoverage$report$ScoverageHtmlWriter$$writePackage$1.apply(ScoverageHtmlWriter.scala:43)
12:58:22 at scoverage.report.ScoverageHtmlWriter$$anonfun$scoverage$report$ScoverageHtmlWriter$$writePackage$1.apply(ScoverageHtmlWriter.scala:43)
12:58:22 at scala.collection.immutable.List.foreach(List.scala:318)
12:58:22 at scoverage.report.ScoverageHtmlWriter.scoverage$report$ScoverageHtmlWriter$$writePackage(ScoverageHtmlWriter.scala:43)
12:58:22 at scoverage.report.ScoverageHtmlWriter$$anonfun$write$1.apply(ScoverageHtmlWriter.scala:33)
12:58:22 at scoverage.report.ScoverageHtmlWriter$$anonfun$write$1.apply(ScoverageHtmlWriter.scala:33)
12:58:22 at scala.collection.immutable.List.foreach(List.scala:318)
12:58:22 at scoverage.report.ScoverageHtmlWriter.write(ScoverageHtmlWriter.scala:33)
12:58:22 at scoverage.ScoverageSbtPlugin$.scoverage$ScoverageSbtPlugin$$writeReports(ScoverageSbtPlugin.scala:190)
12:58:22 at scoverage.ScoverageSbtPlugin$$anonfun$coverageAggregate0$3.apply(ScoverageSbtPlugin.scala:139)
12:58:22 at scoverage.ScoverageSbtPlugin$$anonfun$coverageAggregate0$3.apply(ScoverageSbtPlugin.scala:131)
12:58:22 at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
12:58:22 at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
12:58:22 at sbt.std.Transform$$anon$4.work(System.scala:63)
12:58:22 at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
12:58:22 at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
12:58:22 at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
12:58:22 at sbt.Execute.work(Execute.scala:237)
12:58:22 at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
12:58:22 at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
12:58:22 at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
12:58:22 at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
12:58:22 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:58:22 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
12:58:22 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:58:22 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:58:22 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:58:22 at java.lang.Thread.run(Thread.java:748)
12:58:22 [0m[[31merror[0m] [0m(testing/*:[31mcover

**Comment by gslowikowski** [comment]
You have to set proper source files encoding with:
```
scalacOptions ++= Seq("-encoding", "your_encoding")
```

**Comment by Alex-Yu** [comment]
> You have to set proper source files encoding with:

> scalacOptions ++= Seq("-encoding", "your_encoding")

It's set but don't help.

**Comment by Spyridox** [comment]
I just had the same problem (also, it worked in local but not on GitLab) and adding
`scalacOptions ++= Seq("-encoding", "UTF-8")`
worked

**Comment by bugorz** [comment]
I had the same problem and fix it by 1) or 2)

1. Export the `locale`
```Shell
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8
```
2. Add `-Dfile.encoding=utf-8` right after `sbt`.

**Comment by gslowikowski** [comment]
@bugorz, in your case the encoding is `UTF-8`, so you should just add
```sbt
scalacOptions ++= Seq("-encoding", "UTF-8")
```
to your build.
