### ISSUE TITLE
Because cobertura.sourceforge.net is down. I can't upload a coverage report to coveralls.io

### ISSUE THREAD

**Issue by tanin47** [scoverage/sbt-scoverage#252]
When I go to `http://cobertura.sourceforge.net/xml/coverage-04.dtd`, I get `Project web is currently offline pending the final migration of its data to our new datacenter.`

Since the site is down, I can't upload the coverage report to coveralls.io because the DTD file isn't valid. I'm getting this error:

```
[error] org.xml.sax.SAXParseException; systemId: http://cobertura.sourceforge.net/xml/coverage-04.dtd; lineNumber: 1; columnNumber: 1; The markup declarations contained or pointed to by the document type declaration must be well-formed.
[error] 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
[error] 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDecls(XMLDTDScannerImpl.java:2071)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDTDExternalSubset(XMLDTDScannerImpl.java:306)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1174)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[error] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
[error] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
[error] 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[error] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[error] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
[error] 	at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:41)
[error] 	at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:37)
[error] 	at scala.xml.XML$.loadXML(XML.scala:60)
[error] 	at scala.xml.factory.XMLLoader.loadFile(XMLLoader.scala:48)
[error] 	at scala.xml.factory.XMLLoader.loadFile$(XMLLoader.scala:48)
[error] 	at scala.xml.XML$.loadFile(XML.scala:60)
[error] 	at org.scoverage.coveralls.CoberturaMultiSourceReader.<init>(CoberturaMultiSourceReader.scala:35)
[error] 	at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$1(CoverallsPlugin.scala:104)
[error] 	at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$1$adapted(CoverallsPlugin.scala:54)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (coveralls) org.xml.sax.SAXParseException; systemId: http://cobertura.sourceforge.net/xml/coverage-04.dtd; lineNumber: 1; columnNumber: 1; The markup declarations contained or pointed to by the document type declaration must be well-formed.
```

I wonder if there's a way to avoid depending on `sourceforge.net` (or any remote website) for the dtd file.

**Comment by SethTisue** [comment]
curious: is this issue still current/relevant, should it stay open?

**Comment by ckipp01** [comment]
Seeing that there was no response back here I'll go ahead and close this for now. If this is still an issue, please do report back and I can take a look.
