### ISSUE TITLE
this one throws NullPointerException because it cannot parse the @ alternatives

### ISSUE THREAD

**Issue by YordanGeorgiev** [scoverage/sbt-scoverage#257]
`
      case e @ (_: IOException | _: Exception) => {
        println(e.getMessage)
        return false
      }
`

`
java.lang.NullPointerException
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase$Context.exitScope(GenICode.scala:1921)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.scala$tools$nsc$backend$icode$GenICode$ICodePhase$$genLoad(GenICode.s
cala:924)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.genLoadIf(GenICode.scala:373)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.scala$tools$nsc$backend$icode$GenICode$ICodePhase$$genLoad(GenICode.s
cala:536)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.genLoadLabelDef$1(GenICode.scala:505)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.scala$tools$nsc$backend$icode$GenICode$ICodePhase$$genLoad(GenICode.s
cala:507)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.scala$tools$nsc$backend$icode$GenICode$ICodePhase$$genStat(GenICode.$
cala:181)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$genStat$1.apply(GenICode.scala:155)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$genStat$1.apply(GenICode.scala:155)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.scala$tools$nsc$backend$icode$GenICode$ICodePhase$$genLoad(GenICode.s
cala:922)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$6$$anonfun$apply$2.apply(GenICode.scala:411)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$6$$anonfun$apply$2.apply(GenICode.scala:409)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase$Context$$anonfun$Try$2.apply(GenICode.scala:2083)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase$Context$$anonfun$Try$2.apply(GenICode.scala:2077)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase$Context.Try(GenICode.scala:2077)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.scala$tools$nsc$backend$icode$GenICode$ICodePhase$$genLoad(GenICode.s
cala:590)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:123)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:71)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:148)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:98)
        at sbt.inc.Incremental$.compile(Incremental.scala:71)                                                         [1685/87337]
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
        at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
        at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
        at sbt.Compiler$.compile(Compiler.scala:155)
        at sbt.Compiler$.compile(Compiler.scala:141)
        at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:913)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:904)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:902)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (compile:compileIncremental) java.lang.NullPointerException
[error] Total time: 21 s, completed Apr 16, 2018 3:48:53 PM
`

**Comment by YordanGeorgiev** [comment]
I workaround could be to use the following syntax : 

```
                    case e
                        if (e.isInstanceOf[MeasurementValidationException] || e
                          .isInstanceOf[MeasurementReaderException]) => {
```

**Comment by ckipp01** [comment]
@YordanGeorgiev with the latest version @YordanGeorgiev is this still an issue for you?

**Comment by ckipp01** [comment]
Closing since I believe this is no longer an issue. If you do come across this again, please do comment back in here.
