### ISSUE TITLE
scalac-scoverage-plugin not in libraryDependencies Exception

### ISSUE THREAD

**Issue by btomala** [scoverage/sbt-scoverage#263]
On projects with few modules I try to run scoverage with command: 

> sbt ';scoverageOn;test'

then got such exception:
```
[error] java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
[error]         at scoverage.ScoverageSbtPlugin$.$anonfun$scalacSettings$1(ScoverageSbtPlugin.scala:75)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:844)
[error] (kamon-stackdriver / Compile / compile / scalacOptions) java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
```

**Comment by gslowikowski** [comment]
If you used `coverageOn` (and only misspelled here) there must be something which resets your dependencies.

You always have to add to dependencies with `libraryDependencies += ...` or `libraryDependencies ++= Seq(...)`. Don`t use assignment operator `:=`. Using it you will reset the dependencies and remove the ones, Scoverage just added.

If it's not your case, I need simple project to reproduce the issue.

**Comment by btomala** [comment]
Yes, this is my case, misspelling and overriding dependencies, thanks!
