### ISSUE TITLE
sbt scoverage throwing runtime exceptions

### ISSUE THREAD

**Issue by jeremypulcifer** [scoverage/sbt-scoverage#271]
Using sbt-scoverage v1.5.1: addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")

Scala version 2.12.6:

T0136:backend jpulcifer$ scala -version
Scala code runner version 2.12.6 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.

Note that I'm a scala/sbt newbie, so there is undoubtedly details that I can/should add; please let me know what I can do to assist in diagnosing.

T0136:backend jpulcifer$ sbt -mem 6000 coverage api/allTests:test
[info] Loading global plugins from /Users/jpulcifer/.sbt/0.13/plugins
[info] Loading project definition from /Users/jpulcifer/projects/Collectr/backend/project
[info] Resolving key references (13222 settings) ...
[info] Set current project to build (in build file:/Users/jpulcifer/projects/Collectr/backend/)
[info] Set current project to api (in build file:/Users/jpulcifer/projects/Collectr/backend/)
[info] Defining {.}/*:coverageEnabled
[info] The new value will be used by api/*:libraryDependencies, api/compile:compile::scalacOptions and 35 others.
[info] 	Run `last` for details.
[info] Reapplying settings...
[info] Set current project to api (in build file:/Users/jpulcifer/projects/Collectr/backend/)
[info] Compiling 282 Scala sources and 10 Java sources to /Users/jpulcifer/projects/Collectr/backend/api/target/scala-2.11/classes...
[info] [info] Cleaning datadir [/Users/jpulcifer/projects/Collectr/backend/api/target/scala-2.11/scoverage-data]
[info] [info] Beginning coverage instrumentation
[info] [info] Instrumentation completed [52023 statements]
[info] [info] Wrote instrumentation file [/Users/jpulcifer/projects/Collectr/backend/api/target/scala-2.11/scoverage-data/scoverage.coverage.xml]
[info] [info] Will write measurement data to [/Users/jpulcifer/projects/Collectr/backend/api/target/scala-2.11/scoverage-data]
java.lang.ArrayIndexOutOfBoundsException: 65536
	at scala.tools.asm.ClassReader.readLabel(ClassReader.java:2262)
	at scala.tools.asm.ClassReader.createLabel(ClassReader.java:2269)
	at scala.tools.asm.ClassReader.readFrame(ClassReader.java:2189)
	at scala.tools.asm.ClassReader.readCode(ClassReader.java:1355)
	at scala.tools.asm.ClassReader.readMethod(ClassReader.java:1032)
	at scala.tools.asm.ClassReader.accept(ClassReader.java:708)
	at scala.tools.asm.ClassReader.accept(ClassReader.java:521)
	at scala.tools.asm.ClassWriter.toByteArray(ClassWriter.java:1015)
	at scala.tools.asm.ClassWriter.toByteArray(ClassWriter.java:1018)
	at scala.tools.nsc.backend.jvm.GenASM$JBuilder.writeIfNotTooBig(GenASM.scala:526)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1345)
	at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.emitFor$1(GenASM.scala:198)
	at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:204)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Compiler$.compile(Compiler.scala:141)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:927)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:918)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:916)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (api/compile:compileIncremental) java.lang.ArrayIndexOutOfBoundsException: 65536
[error] Total time: 130 s, completed Dec 13, 2018 12:45:53 PM

**Comment by gslowikowski** [comment]
Interesting. Can you create simple project exposing this issue?

**Comment by gslowikowski** [comment]
@jeremypulcifer do you still need help with this issue?

**Comment by jeremypulcifer** [comment]
I can't reproduce with another codebase; there's clearly something goofy in the original that's making a mess of things (lots of circular references, stuff that I'm not sure why it compiles anyways). Closing.
