### ISSUE TITLE
java.lang.NoSuchMethodError scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(java.lang.String)' with scalate-core_2.12-1.9.6

### ISSUE THREAD

**Issue by zzvara** [scoverage/sbt-scoverage#328]
With SBT `1.5.1` and `sbt-scoverage` 1.7.0, Scala `2.12.13`, 59 out of 767 of our tests fail:

```
29-Apr-2021 13:45:44	2021-04-29 13:45:44.339 ERROR [t-dispatcher-20] i.AbstractSupervisor: Supervisor RestartSupervisor saw failure: 'void scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(java.lang.String)'
29-Apr-2021 13:45:44	java.lang.NoSuchMethodError: 'void scala.tools.nsc.settings.MutableSettings$OutputSetting.value_$eq(java.lang.String)'
29-Apr-2021 13:45:44	        at org.fusesource.scalate.support.ScalaCompiler.generateSettings(ScalaCompiler.scala:132) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
29-Apr-2021 13:45:44	        at org.fusesource.scalate.support.ScalaCompiler.<init>(ScalaCompiler.scala:50) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
29-Apr-2021 13:45:44	        at org.fusesource.scalate.support.ScalaCompiler$.create(ScalaCompiler.scala:37) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
29-Apr-2021 13:45:44	        at org.fusesource.scalate.TemplateEngine.createCompiler(TemplateEngine.scala:232) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
29-Apr-2021 13:45:44	        at org.fusesource.scalate.TemplateEngine.compiler$lzycompute(TemplateEngine.scala:222) ~[scalate-core_2.12-1.9.6.jar:1.9.6]
``` 

We use `org.fusesource.scalate.TemplateEngine` to generate e-mail templates, that is, `scalate-core_2.12-1.9.6`.

What could be the problem?

Thanks!

**Comment by zzvara** [comment]
Not an issue due to Scoverage.
