### ISSUE TITLE
Continuos OutOfMemoryException

### ISSUE THREAD

**Issue by albertoadami** [scoverage/sbt-scoverage#422]
Hi, I'm getting as issue using scoverage sbt plugin.

When running on Jenkins sometimes is going on error as OutOfMemoryException:

```
17:53:29  java.lang.OutOfMemoryError: Metaspace
17:53:29  	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
17:53:29  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
17:53:29  	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
17:53:29  	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:515)
17:53:29  	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:423)
17:53:29  	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:417)
17:53:29  	at java.base/java.security.AccessController.executePrivileged(AccessController.java:782)
17:53:29  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:689)
17:53:29  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:416)
17:53:29  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
17:53:29  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
17:53:29  	at org.scalastyle.CheckerUtils.parseScalariform(Checker.scala:105)
17:53:29  	at org.scalastyle.CheckerUtils.verifySource(Checker.scala:113)
17:53:29  	at org.scalastyle.CheckerUtils.verifyFile(Checker.scala:136)
17:53:29  	at org.scalastyle.ScalastyleChecker.$anonfun$privateCheckFiles$2(Checker.scala:74)
17:53:29  	at org.scalastyle.ScalastyleChecker$$Lambda$9480/0x0000000803222840.apply(Unknown Source)
17:53:29  	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
17:53:29  	at scala.collection.TraversableLike$$Lambda$292/0x00000008014da840.apply(Unknown Source)
17:53:29  	at scala.collection.immutable.List.foreach(List.scala:431)
17:53:29  	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
17:53:29  	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
17:53:29  	at scala.collection.immutable.List.flatMap(List.scala:394)
17:53:29  	at org.scalastyle.ScalastyleChecker.privateCheckFiles(Checker.scala:74)
17:53:29  	at org.scalastyle.ScalastyleChecker.checkFiles(Checker.scala:64)
17:53:29  	at org.scalastyle.sbt.Tasks$.runScalastyle(Plugin.scala:204)
17:53:29  	at org.scalastyle.sbt.Tasks$.doScalastyleWithConfig$1(Plugin.scala:178)
17:53:29  	at org.scalastyle.sbt.Tasks$.doScalastyle(Plugin.scala:192)
17:53:29  	at org.scalastyle.sbt.ScalastylePlugin$.$anonfun$rawScalastyleSettings$3(Plugin.scala:81)
17:53:29  	at org.scalastyle.sbt.ScalastylePlugin$.$anonfun$rawScalastyleSettings$3$adapted(Plugin.scala:68)
17:53:29  	at org.scalastyle.sbt.ScalastylePlugin$$$Lambda$9461/0x0000000803155840.apply(Unknown Source)
17:53:29  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
17:53:29  	at scala.Function1$$Lambda$355/0x000000080152a040.apply(Unknown Source)
17:53:31  java.lang.ClassCastException: class java.lang.OutOfMemoryError cannot be cast to class xsbti.FullReload (java.lang.OutOfMemoryError is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
17:53:31  	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
17:53:31  	at sbt.xMain.run(Main.scala:46)
17:53:31  	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
17:53:31  	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
17:53:31  	at xsbt.boot.Launch$.run(Launch.scala:109)
17:53:31  	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
17:53:31  	at xsbt.boot.Launch$.launch(Launch.scala:117)
17:53:31  	at xsbt.boot.Launch$.apply(Launch.scala:18)
17:53:31  	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
17:53:31  	at xsbt.boot.Boot$.main(Boot.scala:18)
17:53:31  	at xsbt.boot.Boot.main(Boot.scala)
17:53:31  Error during sbt execution: java.lang.ClassCastException: class java.lang.OutOfMemoryError cannot be cast to class xsbti.FullReload (java.lang.OutOfMemoryError is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
````

**Comment by ckipp01** [comment]
Hi @albertoadami looking at your stacktrace I don't believe this has anything to do with scoverage. It's actually the Scalastyle plugin that seems to be throwing the error. I'd recommend opening this there.
