### ISSUE TITLE
NumberFormatException when running coverageReport or coverageAggregated

### ISSUE THREAD

**Issue by tomsfernandez** [scoverage/sbt-scoverage#436]
Hi! I'm getting the following error when using either coverageReport or coverageAggregated. Can you help me out please?

[error] java.lang.NumberFormatException: For input string: "2849015114"
[error] 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[error] 	at java.base/java.lang.Integer.parseInt(Integer.java:652)
[error] 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
[error] 	at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
[error] 	at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
[error] 	at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
[error] 	at scoverage.IOUtils$.$anonfun$invoked$2(IOUtils.scala:80)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scoverage.IOUtils$.$anonfun$invoked$1(IOUtils.scala:78)
[error] 	at scoverage.IOUtils$.$anonfun$invoked$1$adapted(IOUtils.scala:76)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scoverage.IOUtils$.invoked(IOUtils.scala:76)
[error] 	at scoverage.report.CoverageAggregator$.$anonfun$aggregatedCoverage$1(CoverageAggregator.scala:31)
[error] 	at scoverage.report.CoverageAggregator$.$anonfun$aggregatedCoverage$1$adapted(CoverageAggregator.scala:26)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scoverage.report.CoverageAggregator$.aggregatedCoverage(CoverageAggregator.scala:26)
[error] 	at scoverage.report.CoverageAggregator$.aggregate(CoverageAggregator.scala:17)
[error] 	at scoverage.ScoverageSbtPlugin$.$anonfun$coverageAggregate0$3(ScoverageSbtPlugin.scala:136)
[error] 	at scoverage.ScoverageSbtPlugin$.$anonfun$coverageAggregate0$3$adapted(ScoverageSbtPlugin.scala:131)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ckipp01** [comment]
Thanks for reporting @tomsfernandez. The issue is that scoverage tries to call `.toInt` on this and `2849015114` is too large for an `Int`. I'm surprised the number went this high. Is this a large code base you're working with? I'll go ahead and transfer this over to the main scoverage repo as the issue will actually need to be fixed there.
