### ISSUE TITLE
No source root found for `'.../library/src/scala/Tuple.scala' (source roots: '.../src/main/scala/')`

### ISSUE THREAD

**Issue by PanterSoft** [scoverage/sbt-scoverage#478]
Hello,

I am facing an issue which seems to be similar to #444.

I don't actually know where this error comes from. I tried removing every tuple in my program code to get around this problem but even when I have no tuples Inside my program it is still not working.

PS: my Code, Test and `sbt clean coverage test`  run without any flaws only `sbt coverageReport` does not run.

```
[error] java.lang.RuntimeException: No source root found for '/Users/.../library/src/scala/Tuple.scala' (source roots: /Users/.../src/main/scala/')
[error]         at scoverage.reporter.BaseReportWriter.relativeSource(BaseReportWriter.scala:35)
[error]         at scoverage.reporter.BaseReportWriter.relativeSource(BaseReportWriter.scala:23)
[error]         at scoverage.reporter.ScoverageHtmlWriter.writeFile(ScoverageHtmlWriter.scala:84)
[error]         at scoverage.reporter.ScoverageHtmlWriter.$anonfun$writePackage$1(ScoverageHtmlWriter.scala:79)
[error]         at scoverage.reporter.ScoverageHtmlWriter.$anonfun$writePackage$1$adapted(ScoverageHtmlWriter.scala:79)
[error]         at scala.collection.immutable.List.foreach(List.scala:431)
[error]         at scoverage.reporter.ScoverageHtmlWriter.writePackage(ScoverageHtmlWriter.scala:79)
[error]         at scoverage.reporter.ScoverageHtmlWriter.$anonfun$write$1(ScoverageHtmlWriter.scala:69)
[error]         at scoverage.reporter.ScoverageHtmlWriter.$anonfun$write$1$adapted(ScoverageHtmlWriter.scala:69)
[error]         at scala.collection.immutable.List.foreach(List.scala:431)
[error]         at scoverage.reporter.ScoverageHtmlWriter.write(ScoverageHtmlWriter.scala:69)
[error]         at scoverage.ScoverageSbtPlugin$.writeReports(ScoverageSbtPlugin.scala:340)
[error]         at scoverage.ScoverageSbtPlugin$.$anonfun$coverageReport0$1(ScoverageSbtPlugin.scala:236)
[error]         at scoverage.ScoverageSbtPlugin$.$anonfun$coverageReport0$1$adapted(ScoverageSbtPlugin.scala:211)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error]         at java.base/java.lang.Thread.run(Thread.java:1589)
[error] (coverageReport) No source root found for '/Users/.../library/src/scala/Tuple.scala' (source roots: '/Users/.../Chess/src/main/scala/')
```

**Comment by ckipp01** [comment]
Hey @PanterSoft this should be fixed in the latest versions of Scala 3. Could you test with `3.2.2-RC1-bin-20221101-d84007c-NIGHTLY` and see if your issue still exists? That is assuming you're using Scala 3.

**Comment by PanterSoft** [comment]
Hey @ckipp01 I tried it and it worked. The nightly build did the trick. 

thanks for the help
