### ISSUE TITLE
NoDenotation error with scala 3.3.0

### ISSUE THREAD

**Issue by bczhaoa** [scoverage/sbt-scoverage#517]
i can  run command  `sbt test` success.

bug i run `sbt clean coverage test coverageReport` failed

detail: [error] (Compile / compileIncremental) java.lang.AssertionError: NoDenotation.owner

**Comment by bczhaoa** [comment]
[info] compiling 66 Scala sources to D:\30023142\scalaDemo\target\scala-3.3.0\classes ...
java.lang.AssertionError: NoDenotation.owner while running MegaPhase{crossVersionChecks, protectedAccessors, extmethods, uncacheGivenAliases, elimByName, hoistSuperArgs, forwardDepChecks, specializeApplyMethods, tryCatchPatter
ns, patternMatcher} on D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\DoConstructor.scala
[info] exception occurred while compiling D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\Person.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test01_Lambda.scala, D:\30023142\scala
Demo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test02_Lambda.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test03_Lambda.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn
\advance\Test04_Lambda.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test05_Closure_Currying.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test05_Lambda.scala, D:\3
0023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test06_Fact.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test07_ControAbstraction.scala, D:\30023142\scalaDemo\src\main\scala\co
m\huawei\zbc\sbt\learn\advance\Test08_MyWhile.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test09_Lazy.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\DoDataType.scala
, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\DoDataTypeConversion.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\DoFor.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei
\zbc\sbt\learn\basic\DoOperator.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\DoStdIn.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\HelloScala.scala, D:\30023142\scalaD
emo\src\main\scala\com\huawei\zbc\sbt\learn\basic\Student.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\Variable.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test
01_ImmutableArray.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test02_ArrayBuffer.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test03_Array_And_ArrayBuffer.
scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test04_MulArray.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test05_ImmutableList.scala, D:\30023142\scalaDemo\
src\main\scala\com\huawei\zbc\sbt\learn\collection\Test06_ListBuffer.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test07_ImmutableSet.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zb
c\sbt\learn\collection\Test08_mutableSet.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test09_ImmutableMap.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test1
0_mutableMap.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test11_Tuple.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test12_Seq.scala, D:\30023142\scalaDemo\
src\main\scala\com\huawei\zbc\sbt\learn\collection\Test12_SimpleFunction.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test13_HighLevelFuncation_Map.scala, D:\30023142\scalaDemo\src\main\scala
\com\huawei\zbc\sbt\learn\collection\Test14_HighLevelFuncation_Reduce.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test15_MergeMap.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\s
bt\learn\collection\Test16_WordCount.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test18_WordCountPlus.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test19_Q
ueue.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test20_Parallel.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\DoFor1.scala, D:\30023142\scalaDemo\src\main\sca
la\com\huawei\zbc\sbt\learn\control\DoIfElse.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\Test04_For.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\Test05_While.sca
la, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\Test06_Break.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\Test07_Function.scala, D:\30023142\scalaDemo\src\main\scala\co
m\huawei\zbc\sbt\learn\control\Test08_Function02.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\io\FileIo.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\DoConstructor.scala, D:\3
0023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test01_TestPkg.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test02_Package.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sb
t\learn\oop\Test03_Class.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test03_Class1.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test04_Constructor1.scala, D:\30023142\sc
alaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test05_Dynamic.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test06_AbstractClass.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\le
arn\oop\Test07_AnnoymousClass.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test08_Object.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test09_Singleton.scala, D:\30023142\
scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test10_Trait.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test11_Extend.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop
\Test12_Trait02.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test13_Trait03.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test15_Enum.scala, D:\30023142\scalaDemo\src\main
\scala\com\huawei\zbc\sbt\learn\oop\Test16_App_And_Type.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\package.scala, D:\30023142\scalaDemo\src\main\scala\main.scala
java.lang.AssertionError: NoDenotation.owner while compiling D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\Person.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test01_Lambda.scala
, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test02_Lambda.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test03_Lambda.scala, D:\30023142\scalaDemo\src\main\scala\com\h
uawei\zbc\sbt\learn\advance\Test04_Lambda.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test05_Closure_Currying.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test05
_Lambda.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test06_Fact.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test07_ControAbstraction.scala, D:\30023142\scalaDem
o\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test08_MyWhile.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\advance\Test09_Lazy.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\bas
ic\DoDataType.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\DoDataTypeConversion.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\DoFor.scala, D:\30023142\scalaDemo\src\ma
in\scala\com\huawei\zbc\sbt\learn\basic\DoOperator.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\DoStdIn.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\HelloScala.scala,
 D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\Student.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\basic\Variable.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\le
arn\collection\Test01_ImmutableArray.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test02_ArrayBuffer.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test03_Arr
ay_And_ArrayBuffer.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test04_MulArray.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test05_ImmutableList.scala, D:\
30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test06_ListBuffer.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test07_ImmutableSet.scala, D:\30023142\scalaDemo\src\main\
scala\com\huawei\zbc\sbt\learn\collection\Test08_mutableSet.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test09_ImmutableMap.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\lea
rn\collection\Test10_mutableMap.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test11_Tuple.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test12_Seq.scala, D:\
30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test12_SimpleFunction.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test13_HighLevelFuncation_Map.scala, D:\30023142\scala
Demo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test14_HighLevelFuncation_Reduce.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test15_MergeMap.scala, D:\30023142\scalaDemo\src\main\sca
la\com\huawei\zbc\sbt\learn\collection\Test16_WordCount.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test18_WordCountPlus.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\
collection\Test19_Queue.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\collection\Test20_Parallel.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\DoFor1.scala, D:\30023142\sca
laDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\DoIfElse.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\Test04_For.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\contr
ol\Test05_While.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\Test06_Break.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\control\Test07_Function.scala, D:\30023142\scalaDem
o\src\main\scala\com\huawei\zbc\sbt\learn\control\Test08_Function02.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\io\FileIo.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\DoCons
tructor.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test01_TestPkg.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test02_Package.scala, D:\30023142\scalaDemo\src\main\scal
a\com\huawei\zbc\sbt\learn\oop\Test03_Class.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test03_Class1.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test04_Constructor1.sc
ala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test05_Dynamic.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test06_AbstractClass.scala, D:\30023142\scalaDemo\src\main\scala\co
m\huawei\zbc\sbt\learn\oop\Test07_AnnoymousClass.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test08_Object.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test09_Singleton.
scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test10_Trait.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test11_Extend.scala, D:\30023142\scalaDemo\src\main\scala\com\huawe
i\zbc\sbt\learn\oop\Test12_Trait02.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test13_Trait03.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test15_Enum.scala, D:\30023142
\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\Test16_App_And_Type.scala, D:\30023142\scalaDemo\src\main\scala\com\huawei\zbc\sbt\learn\oop\package.scala, D:\30023142\scalaDemo\src\main\scala\main.scala
[error] ## Exception when compiling 66 sources to D:\30023142\scalaDemo\target\scala-3.3.0\classes
[error] java.lang.AssertionError: NoDenotation.owner
[error] dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2576)
[error] dotty.tools.dotc.transform.HoistSuperArgs$Hoister.hoistSuperArgsFromCall(HoistSuperArgs.scala:185)
[error] dotty.tools.dotc.transform.HoistSuperArgs$Hoister.hoistSuperArgsFromConstr(HoistSuperArgs.scala:218)
[error] dotty.tools.dotc.transform.HoistSuperArgs.$anonfun$7(HoistSuperArgs.scala:230)
[error] dotty.tools.dotc.core.Decorators$.loop$1(Decorators.scala:94)
[error] dotty.tools.dotc.core.Decorators$.mapconserve(Decorators.scala:110)
[error] dotty.tools.dotc.transform.HoistSuperArgs.transformTypeDef(HoistSuperArgs.scala:230)
[error] dotty.tools.dotc.transform.MegaPhase.goTypeDef(MegaPhase.scala:995)
[error] dotty.tools.dotc.transform.MegaPhase.goTypeDef(MegaPhase.scala:996)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:256)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:425)
[error] dotty.tools.dotc.transform.MegaPhase.loop$1(MegaPhase.scala:438)
[error] dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:438)
[error] dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:379)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:382)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:466)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:324)
[error] scala.collection.immutable.List.map(List.scala:250)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:328)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:247)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:263)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:271)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:280)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:280)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:195)
[error] dotty.tools.dotc.Run.compile(Run.scala:179)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:505)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2369)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2319)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:31)
[error] sbt.internal.io.Retry$.apply(Retry.scala:47)
[error] sbt.internal.io.Retry$.apply(Retry.scala:29)
[error] sbt.internal.io.Retry$.apply(Retry.scala:24)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2317)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] sbt.Execute.work(Execute.scala:292)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:833)
[error]
[error] java.lang.AssertionError: NoDenotation.owner
[error]         at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2576)
[error]         at dotty.tools.dotc.transform.HoistSuperArgs$Hoister.hoistSuperArgsFromCall(HoistSuperArgs.scala:185)
[error]         at dotty.tools.dotc.transform.HoistSuperArgs$Hoister.hoistSuperArgsFromConstr(HoistSuperArgs.scala:218)
[error]         at dotty.tools.dotc.transform.HoistSuperArgs.$anonfun$7(HoistSuperArgs.scala:230)
[error]         at dotty.tools.dotc.core.Decorators$.loop$1(Decorators.scala:94)
[error]         at dotty.tools.dotc.core.Decorators$.mapconserve(Decorators.scala:110)
[error]         at dotty.tools.dotc.transform.HoistSuperArgs.transformTypeDef(HoistSuperArgs.scala:230)
[error]         at dotty.tools.dotc.transform.MegaPhase.goTypeDef(MegaPhase.scala:995)
[error]         at dotty.tools.dotc.transform.MegaPhase.goTypeDef(MegaPhase.scala:996)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:256)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:425)
[error]         at dotty.tools.dotc.transform.MegaPhase.loop$1(MegaPhase.scala:438)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:438)
[error]         at dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:379)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:382)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:454)
[error]         at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:466)
[error]         at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:324)
[error]         at scala.collection.immutable.List.map(List.scala:250)
[error]         at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:328)
[error]         at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:247)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
[error]         at dotty.tools.dotc.Run.runPhases$1(Run.scala:263)
[error]         at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:271)
[error]         at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:280)
[error]         at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error]         at dotty.tools.dotc.Run.compileUnits(Run.scala:280)
[error]         at dotty.tools.dotc.Run.compileSources(Run.scala:195)
[error]         at dotty.tools.dotc.Run.compile(Run.scala:179)
[error]         at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
[error]         at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error]         at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error]         at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
[error]         at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
[error]         at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error]         at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2317)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error]         at sbt.Execute.work(Execute.scala:292)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
[error] (Compile / compileIncremental) java.lang.AssertionError: NoDenotation.owner
[error] Total time: 7 s, completed 2023骞?0鏈?3鏃?涓嬪崍4:52:33

**Comment by bczhaoa** [comment]
i try `sbt clean jacoco` https://github.com/sbt/sbt-jacoco success

**Comment by ckipp01** [comment]
Thanks for the report @bczhaoa, but it's literally impossible to reproduce what you're experiencing without some reproduction code that illustrates what you're hitting on. Can you minimize and provide an example for someone to try and reproduce this on their machine?
