### ISSUE TITLE
Synthetic tree contains nonsynthetic tree

### ISSUE THREAD

**Issue by MeiSign** [scoverage/sbt-scoverage#72]
I have just tried to upgrade my play project from 0.99.4 to 1.0.1 but when I try to run sbt coverage test I get a Synthetic tree [3300] contains nonsynthetic tree [3299] Error while compiling the Global Object of my play application.
I think this problem only occurs if your use MacWire

The codesnippet shown in the exception looks like this:

```
[error] 
[error]   last tree to typer: Ident(controllerClass)
[error]               symbol: value controllerClass (flags: <param> <triedcooking>)
[error]    symbol definition: controllerClass: Class[A]
[error]                  tpe: Class[A]
[error]        symbol owners: value controllerClass -> method getControllerInstance -> object Global -> package <empty>
[error]       context owners: method getControllerInstance -> object Global -> package <empty>
[error] 
[error] == Enclosing template or block ==
[error] 
[error] Apply(
[error]   "wired"."lookupSingleOrThrow"
[error]   "controllerClass" // controllerClass: Class[A], tree.tpe=Class[A]
[error] )
[error] 
[error] == Expanded type of tree ==
[error] 
[error] AliasTypeRef(
[error]   pre = SingleType(pre = ThisType(package scala), object Predef)
[error]   Alias(type Class[T] = Class[T])
[error]   args = List(SkolemTypeRef(TypeSkolem(A)))
[error]   normalize = TypeRef(
[error]     TypeSymbol(
[error]       final class Class[T] extends Serializable with GenericDeclaration with Type with AnnotatedElement
[error]       
[error]     )
[error]     args = List(SkolemTypeRef(TypeSkolem(A)))
[error]   )
[error] )
[error] 
```

I will try to reprocude this issue in a minimal project and add it here.

**Comment by mcanlas** [comment]
Is this supposed to work in 2.10.5, which as a rangepos fix, or is that a different issue?

**Comment by sksamuel** [comment]
Yes it should work in 2.10.5 but I've not tried it.

**Comment by marcospereira** [comment]
Looks like this issue is not fixed entirely. I was trying to add scoverage to Playframework and step into this problem.

## How to reproduce

1. Clone [Playframework](https://github.com/playframework/playframework/) project.
2. Add scoverage plugin to `playframework/framework/project/plugins.sbt` file.
3. Inside `playframework/framework/` directory execute `sbt clean coverage test`.

It fails with the following stack trace:

```
scala.tools.nsc.interactive.RangePositions$ValidateException: Synthetic tree [9356] contains nonsynthetic tree [9338]
	at scala.tools.nsc.interactive.RangePositions$class.positionError$1(RangePositions.scala:201)
	at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:218)
	at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
	at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
	at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
	at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
	at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
	at scala.tools.nsc.interactive.RangePositions$class.validatePositions(RangePositions.scala:246)
	at xsbt.CachedCompiler0$$anon$1.validatePositions(CompilerInterface.scala:150)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:100)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:91)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:91)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:91)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
	at sbt.inc.Incremental$.compile(Incremental.scala:61)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:128)
	at sbt.Compiler$.compile(Compiler.scala:114)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:814)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:805)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:803)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (SBT-Plugin/compile:compileIncremental) scala.tools.nsc.interactive.RangePositions$ValidateException: Synthetic tree [9356] contains nonsynthetic tree [9338]
``` 
## Details

1. Play is using scala 2.10.5/2.11.6 and sbt 0.13.8
2. java version "1.8.0_45"

**Comment by jieyang1** [comment]
Scala 2.10.4/2.10.5, SBT 0.13.7, sbt-scoverage 1.0.0 and above
The error is still there
[error] (common/compile:compile) scala.tools.nsc.interactive.RangePositions$ValidateException: Synthetic tree [228456] contains nonsynthetic tree [228438]"

**Comment by slavaschmidt** [comment]
Scala 2.10.5, SBT 0.13.8, set-scoverage 1.3.3
The issue is still not resolved: 

======= Position error
Synthetic tree [1736] contains nonsynthetic tree [1731]

**Comment by slavaschmidt** [comment]
@marcospereira Any chance this issue get's some attention again?

**Comment by rafael-brandao** [comment]
I was having the exact same issue. I fixed it by turning off coverageHighlighting option in build.sbt. My project scalaVersion is set to 2.10.6, since it is a plugin project.
```scala
coverageHighlighting := false
```
