### ISSUE TITLE
CodeGrid should specify the encoding while reading the contents of the MeasuredFie

### ISSUE THREAD

**Issue by slavaschmidt** [scoverage/sbt-scoverage#86]
Line 46 of the version 1.0.1: 
```
private def source(mfile: MeasuredFile): String = Source.fromFile(mfile.source).mkString
```

fails on some systems with following exception:
```
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:338)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.read(BufferedReader.java:175)
	at scala.io.BufferedSource$$anonfun$iter$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(BufferedSource.scala:38)
	at scala.io.Codec.wrap(Codec.scala:68)
	at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
	at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
	at scala.collection.Iterator$$anon$17.hasNext(Iterator.scala:511)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.io.Source.hasNext(Source.scala:226)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.io.Source.foreach(Source.scala:178)
	at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:320)
	at scala.io.Source.addString(Source.scala:178)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:286)
	at scala.io.Source.mkString(Source.scala:178)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:288)
	at scala.io.Source.mkString(Source.scala:178)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:290)
	at scala.io.Source.mkString(Source.scala:178)
	at scoverage.report.CodeGrid.source(CodeGrid.scala:46)
	at scoverage.report.CodeGrid.<init>(CodeGrid.scala:15)
	at scoverage.report.ScoverageHtmlWriter.filePage(ScoverageHtmlWriter.scala:79)
	at scoverage.report.ScoverageHtmlWriter.scoverage$report$ScoverageHtmlWriter$$writeFile(ScoverageHtmlWriter.scala:42)
	at scoverage.report.ScoverageHtmlWriter$$anonfun$scoverage$report$ScoverageHtmlWriter$$writePackage$1.apply(ScoverageHtmlWriter.scala:35)
	at scoverage.report.ScoverageHtmlWriter$$anonfun$scoverage$report$ScoverageHtmlWriter$$writePackage$1.apply(ScoverageHtmlWriter.scala:35)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scoverage.report.ScoverageHtmlWriter.scoverage$report$ScoverageHtmlWriter$$writePackage(ScoverageHtmlWriter.scala:35)
	at scoverage.report.ScoverageHtmlWriter$$anonfun$write$1.apply(ScoverageHtmlWriter.scala:23)
	at scoverage.report.ScoverageHtmlWriter$$anonfun$write$1.apply(ScoverageHtmlWriter.scala:23)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scoverage.report.ScoverageHtmlWriter.write(ScoverageHtmlWriter.scala:23)
	at scoverage.ScoverageSbtPlugin.scoverage$ScoverageSbtPlugin$$writeReports(ScoverageSbtPlugin.scala:202)
	at scoverage.ScoverageSbtPlugin$$anonfun$postTestReport$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(ScoverageSbtPlugin.scala:135)
	at scoverage.ScoverageSbtPlugin$$anonfun$postTestReport$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(ScoverageSbtPlugin.scala:134)
	at scala.Option.foreach(Option.scala:236)
	at scoverage.ScoverageSbtPlugin$$anonfun$postTestReport$1$$anonfun$apply$1.apply$mcV$sp(ScoverageSbtPlugin.scala:133)
	at sbt.Tests$$anonfun$Cleanup$1.apply(Tests.scala:53)
	at sbt.Tests$$anonfun$Cleanup$1.apply(Tests.scala:53)
	at sbt.Tests$$anonfun$sbt$Tests$$partApp$1$1$$anonfun$apply$1.apply$mcV$sp(Tests.scala:160)
	at sbt.Tests$$anonfun$sbt$Tests$$fj$1$1.apply(Tests.scala:159)
	at sbt.Tests$$anonfun$sbt$Tests$$fj$1$1.apply(Tests.scala:159)
	at sbt.std.TaskExtra$$anon$1$$anonfun$fork$1$$anonfun$apply$1.apply(TaskExtra.scala:99)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by d1egoaz** [comment]
I have the same problem, but not in my local dev box, but in a Jenkins(linux) server. Maybe is something related to the encoding configuration of that server.

I think the bug is in other project [scalac-scoverage-plugin](https://github.com/scoverage/scalac-scoverage-plugin) in the file:  `src/main/scala/scoverage/report/CodeGrid.scala`

I made some tests in CodeGrid.scala with the following change and works for me
```
  def source(filePath: String): String = {
    implicit val codec = Codec("UTF-8")
    codec.onMalformedInput(CodingErrorAction.REPLACE)
    codec.onUnmappableCharacter(CodingErrorAction.REPLACE)
 
    Source.fromFile(filePath).mkString
  }
```

Now I need to make a PR to that project.

**Comment by d1egoaz** [comment]
hmm but I don't know if its valid to assume that everyone is going to use UTF-8 :/
So I don't know if this would be a valid PR.

**Comment by d1egoaz** [comment]
I just solve my problem configuring in Jenkins JVM Flags of the Build SBT the JVM flag; 
`-Dfile.encoding=utf-8`
